### At first perform source build ###
FROM starwarsfan/cmake-builder-fedora:1.0
MAINTAINER Yves Schumann <yves@eisfair.org>

COPY . /demo-app

RUN mkdir /demo-app/build \
 && cd /demo-app/build \
 && cmake .. \
 && cmake --build .

RUN echo "Build is finished now, just execute result right here to show something on the log:" \
 && /demo-app/build/hello-world
